### ISSUE TITLE
Remove logging to standard output

### ISSUE THREAD

**Issue by epsleq0** [saferwall/pe#20]
`saferwall/pe` makes use of the `log` package in [`exception.go`](https://github.com/saferwall/pe/blob/00ebfd451e6ce4e9e69b6b6aa68cfe7d9df368a4/exception.go#L407) which prevents me from using it in a CLI application:

> 2022/03/31 03:14:39 Wrong unwind opcode 15
> 2022/03/31 03:14:39 Wrong unwind opcode 15
> 2022/03/31 03:14:39 Wrong unwind opcode 14
> 2022/03/31 03:14:39 Wrong unwind opcode 13
> 2022/03/31 03:14:39 Wrong unwind opcode 12
> …

`saferwall/pe` should not use logging on its own, as this often results in unexpected behavior.

The question is: shall we just drop that line and the `log` depedency as it is just a warning or do we need some logger-Interface/callback methods to be passed in the constructors?

**Comment by LordNoteworthy** [comment]
Hello @epsleq0 

You are right, the package should offer a way to use its own logger. @secDre4mer opened a PR in the past and we discussed this.

Indeed, I was actually doing some work just this week on what would be the appropriate interface to provide.

I  might need your input on this.

First solution is to use an interface that looks like this:

```go
// Logger is a generic logging interface
type Logger interface {
	// Init initialises options
	Init(options ...Option) error
	// The Logger options
	Options() Options
	// Fields set fields to always be logged
	Fields(fields map[string]interface{}) Logger
	// Log writes a log entry
	Log(level Level, v ...interface{})
	// Logf writes a formatted log entry
	Logf(level Level, format string, v ...interface{})
	// String returns the name of logger
	String() string
}
```

The other interface is a bit more verbose and split the logging level methods:

```go
// Logger is a logger that supports log levels, context and structured logging.
type Logger interface {
	// With returns a logger based off the root logger and decorates it with
	// the given context and arguments.
	With(ctx context.Context, args ...interface{}) Logger

	// Debug uses fmt.Sprint to construct and log a message at DEBUG level
	Debug(args ...interface{})
	// Info uses fmt.Sprint to construct and log a message at INFO level
	Info(args ...interface{})
	// Error uses fmt.Sprint to construct and log a message at ERROR level
	Error(args ...interface{})

	// Debugf uses fmt.Sprintf to construct and log a message at DEBUG level
	Debugf(format string, args ...interface{})
	// Infof uses fmt.Sprintf to construct and log a message at INFO level
	Infof(format string, args ...interface{})
	// Errorf uses fmt.Sprintf to construct and log a message at ERROR level
	Errorf(format string, args ...interface{})
}
```

What do you think it would be more appropriate ?

There are several places in this pkg that I would probably just to issue a debug log or a warning log, so supporting levels would be helpful. Moreover, we need some structured logging, as in saferwall.com, we scan a lot of samples and we index them in ES, it would be nice sometimes to search the logs for a particular field rather than having to use regex.

**Comment by epsleq0** [comment]
Hello @LordNoteworthy. The second approach makes it necessary to implement at least `2*n` functions for each adapter, where `n` is the number of "imaginary" log levels. I would definitely prefer mapping a log level here to a log level of my adaptee.

On the other hand, the first approach has a very extensive interface where I wonder: why do we need all these functions?

I suggest a mix of the two suggestions above:

```go
// Logger is a logger that supports log levels, context and structured logging.
type Logger interface {
	// WithFields set fields to always be logged.
	WithFields(fields map[string]interface{}) Logger
	// Log writes a log entry.
	Log(ctx context.Context, level Level, message string)
}
```

or a variant that is highly inspired by [`jackc/pgx`](https://github.com/jackc/pgx/blob/3ce50c079e874c87c4d53eada409738d8504bac6/logger.go#L47):

```go
// Logger is a logger that supports log levels, context and structured logging.
type Logger interface {
	// Log writes a log entry.
	Log(ctx context.Context, level Level, message string, fields map[string]interface{})
}
```

From what I have seen so far in `saferwall/pe`, reusing loggers with fields should be beneficial.

**Comment by LordNoteworthy** [comment]
>  Hello @LordNoteworthy. The second approach makes it necessary to implement at least 2*n functions for each adapter, where n is the number of "imaginary" log levels. I would definitely prefer mapping a log level here to a log level of my adaptee.

Hi @epsleq0, I fully agree, normally interfaces has to be a small as possible so the abstraction is big.

> Furthermore, I see various issues for both approaches with respect to logging unstructured args ...interface{} instead of a single message string. I always thought that was what additional fields were for.

The `args ...interface{}` is practical, otherwise you would need always to do an sprintf when you need to log a message that looks like: `log("failed with: %v", err)`, which is the case pretty much in most of the log lines inside this pkg.

The *additional fields* are for logging something that you always want to include in your log message, for example in batch processing, you want to include the `sha256` so later you can easily filter out by that field, it is also very common in web services to include some fields during the life span of a request.

I will go with something similar to the last interface  you shared, maybe without the context

**Comment by epsleq0** [comment]
Great @LordNoteworthy ! I would probably drop the context as well, because it should be possible to construct and pass a "context-aware" logger at any time.

Let me know if I can help somewhere.

> The `args ...interface{}` is practical, otherwise you would always need to do a `sprintf` [...]

This is correct and gives a right of existence to the function `Logf` in the first approach and `Debugf`, `Infof` and `Errorf` in the second approach.

On the other hand, the function `Log(level Level, v ...interface{})` in the first approach and the functions `Debug(args ...interface{})`, `Info(args ...interface{})`, and `Error(args ...interface{})` in the second approach are still problematic. I guess it's just a typo I stumbled upon?!
I'd hate to delegate the decision to the adapter developer how to handle the two valid calls like `Debug("foo", []byte("bar"), struct{}{}, nil)` or `Info()`; with a string message and optional fields, as in `Log(level Level, message string, fields map[string]interface{})`, it is clear what to do.

**Comment by LordNoteworthy** [comment]
Hi @epsleq0 

After reading through many projects that designs a logging interface, I end up with the following simple interface that I borrowed from the [kratos](https://github.com/go-kratos/kratos/tree/main/log)

```go
// Logger is a logger interface.
type Logger interface {
	Log(level Level, keyvals ...interface{}) error
}
```

You only need to implement one method. But the nice thing that there is a helper.go and a filter.go that the `pe` pkg use internally to wrap the calls to `Infof` and similar calls. Have a look at the `README.md` file inside the `log` directory that shows some example how to use it.
