### ISSUE TITLE
How to write to file? 

### ISSUE THREAD

**Issue by MosheMendel18** [saferwall/pe#98]
I asked this on stackoverflow, but then I realized you probably know best. If you can help me out, it would be awesome. See the full question here: https://stackoverflow.com/questions/78762369/set-properties-of-an-exe-using-golang

**Comment by LordNoteworthy** [comment]
I am not sure I understood what you're aiming for.

If you modified the `peFile.Anomalies`, and you reparse the file, ofc the value will be gone.

Why not just keep a map that holds filepath -> pefile struct ?

**Comment by MosheMendel18** [comment]
@LordNoteworthy I don't understand. I want to change the file properties. Let's use `peFile.Anomalies` as an example property. I want to 

1. change that property (as easy as `peFile.Anomalies = []string{"new stuff"}`)
2. write that change to the actual file

That last part is the part I don't know how to do. So the goal is to change the file such that if you run `pe.New()` and `pe.Parse()` again, it should hold the value the next time you rerun your Go script (or check the file properties a different way). I know it's possible for a user to open a file's properties and change them manually.

The reason a map wouldn't be sufficient is because I need the file to contain the information even after the script has been closed, which means, of course, that all memory has been cleared.

**Comment by LordNoteworthy** [comment]
I see, this is not possible, simply because a PE parser is not supposed to do something like this. 

Anomalies are extracted from a file because some PE fields have abnormal values, you can write an anomaly back to a PE file, it does not make sense.

There is many ways you can do what you want, simply keep track in a KV embedded database, the list of anomalies as value, and the filepath as key.
